### ISSUE TITLE
Superstream search

### ISSUE THREAD

**Issue by hvroun1** [jmir1/aniyomi-extensions#1009]
### Source information and language

Superstream 13.3 English 

### Steps to reproduce

Superstream extension search function has stopped working but shows already added in library work fine. What could be the issue?

### Expected behavior

Search should work as previous times 

### Actual behavior

Superstream extension search function has stopped working but shows already added in library work fine. What could be the issue?

### Aniyomi version

0.12.3.8

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Samfun75** [comment]
It is an issue from the source not the extension. we've to wait until the source's search functionality works again

**Comment by hvroun1** [comment]
What is the source address? I have tried WebView from the app but it failed to load.

**Comment by Samfun75** [comment]
> What is the source address? I have tried WebView from the app but it failed to load.

Yeah, the source doesn't have a website

> Kindly Sir , When will v0.13.5 be released?

Soon<sup>TM</sup>

**Comment by Samfun75** [comment]
This can be closed as it is back to normal now.

**Comment by jmir1** [comment]
> Will there ever be a version for ios?

nope.
