### ISSUE TITLE
AsianLoad and Dramacool unable to play any series

### ISSUE THREAD

**Issue by Liking-Link** [jmir1/aniyomi-extensions#1011]
### Source information and language

AsianLoad v13.18/ Dramacool v13.24

### Steps to reproduce

AsianLoad or Dramacool On library or after searching on application unable to play any episodes of k series.

### Expected behavior

It should have worked fine but it's not playing any series at all.

### Actual behavior

in Dramacool it says this extension for temporary uses on override url( also update extension will erase this setting) Nothing new to update.

### Aniyomi version

0.12.3.8

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by qryptonique** [comment]
Hi! I had these issues and they just got a fix in DramaCool 13.25 and AsianLoad 13.19. Please update your extensions to check. Cheers!

**Comment by Liking-Link** [comment]
It's fixed
