### ISSUE TITLE
[Bug] <SuperStream>: <Search does not work correctly>

### ISSUE THREAD

**Issue by TheWrightStuff1994** [jmir1/aniyomi-extensions#1028]
## Device information
- Aniyomi version: App version: 0.14.2.0-5846 (standard, aa69f47a1, 93, 2022-11-15T10:50Z)
-Android version: 10 (SDK 29)
-Android build ID: QDF30.130-42-5-17
-Device brand: motorola
-Device manufacturer: motorola
-Device name: foles
-Device model: moto z4
-Device product name: foles_vzw

## Source information
- Name: SuperStream 
- Extension version: 13.4

## Steps to reproduce
1. First Step Search for Movie/Tv Show
2. Second Step 
![Screenshot_20221118-062019](https://user-images.githubusercontent.com/7861649/202778018-b7d229cd-cecd-4ef9-832e-0ca64df75157.png)
![Screenshot_20221118-121334](https://user-images.githubusercontent.com/7861649/202778056-04a36004-5b46-4402-a925-2f1e5eb90087.png)

### Expected behavior
Search for the correct thing

### Actual behavior
Nothing shows up

**Comment by bobogagabobo** [comment]
I'm having the same problem

**Comment by TheWrightStuff1994** [comment]
> I'm having the same problem

Yeah it's weird too because like 5:00 a.m. I could search stuff but then afterwards I can't anything anymore...

**Comment by TheWrightStuff1994** [comment]
Still wonky and not really fix. Still get these messages on the extension...
![Screenshot_20221122-091453](https://user-images.githubusercontent.com/7861649/203351568-363356c1-a802-4d33-bd09-a2dc1fe95c3a.png)
![Screenshot_20221122-043544](https://user-images.githubusercontent.com/7861649/203351690-c91e6b70-1ab8-4cea-9eca-f854cda69d75.png)
