### ISSUE TITLE
[Bug] SuperStream: Search still not working well

### ISSUE THREAD

**Issue by TheWrightStuff1994** [jmir1/aniyomi-extensions#1038]
## Device information
App version: 0.14.2.0-5846 (standard, aa69f47a1, 93, 2022-11-15T10:50Z)
Android version: 10 (SDK 29)
Android build ID: QDF30.130-42-5-17
Device brand: motorola
Device manufacturer: motorola
Device name: foles
Device model: moto z4
Device product name: foles_vzw

## Source information
- Name: SuperStream 
- Extension version: 13.5

## Steps to reproduce
1. Search for Movie and or tv show

### Expected behavior
For it to search the thing I'm searching for

### Actual behavior
Doesn't search for the thing I'm searching for

## Other details
![Screenshot_20221122-091453](https://user-images.githubusercontent.com/7861649/203353821-f6f490cc-4386-401c-b2e7-df19da9b2787.png)
![Screenshot_20221122-092349](https://user-images.githubusercontent.com/7861649/203353925-37835965-445e-446a-bbd4-39f1fbe01bb7.png)

**Comment by Samfun75** [comment]
That is a problem from the source, just retry. What is fixed is the timeout problem!
