### ISSUE TITLE
Add more Anime extensions 

### ISSUE THREAD

**Issue by Ash267** [jmir1/aniyomi-extensions#11]
I would really appreciate it if you could add more Anime extensions because when downloading some episodes i get this error ![Screenshot_20210605_201032.jpg](https://user-images.githubusercontent.com/65956967/120895654-a0ea1e80-c63b-11eb-9ec4-ea24a31e26ba.jpg)
Overall the app is super awesome

**Comment by jmir1** [comment]
care to elaborate?

**Comment by xXAceNoob** [comment]
I'd love to see Genoanime.com and/or Zoro.to as an extension. For the dubs and stuff.

**Comment by jmir1** [comment]
closing cause kinda useless source request if no source is specified
