### ISSUE TITLE
Animixplay - Error Getting Links

### ISSUE THREAD

**Issue by Akip17** [jmir1/aniyomi-extensions#1104]
### Source information and language

Animixplay 13.13 (English)

### Steps to reproduce

1. Choose any episode of any anime.
2. Press play button.
3. Video cannot be played.
4. Error message popup, "Error getting links"

### Expected behavior

It should play the video as usual.

### Actual behavior

The app plays the video normally without any issues before this.

### Aniyomi version

0.12.3.8

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Solovertical** [comment]
I think website internal player are unavailable , they said it will fix automatically and also they are working on what they do to fix that, They already mentioned that in their discord(Anime discord not Aniyomi) and it's not related to Aniyomi .
I'm not a dev hope it help

**Comment by Akip17** [comment]
Oh I see. Thank you for the information. Have a good day to you!

**Comment by Akip17** [comment]
> I think website internal player are unavailable , they said it will fix automatically and also they are working on what they do to fix that, They already mentioned that in their discord(Anime discord not Aniyomi) and it's not related to Aniyomi . I'm not a dev hope it help

Now It's gone forever. This is sad.

**Comment by Solovertical** [comment]
> 

Yup it kinda sad to know that they don't return, There a fake scrapper of animixplay, i don't know would they add that as an extension or not.
