### ISSUE TITLE
[Source Request] <Kamyroll Extension>

### ISSUE THREAD

**Issue by Solovertical** [jmir1/aniyomi-extensions#1117]
## Source website
- Name: Kamyroll 
- Link: 
- Language(s): En

## Other details
Well i don't have link but this extension is implemented in saikou and there no option to download ep, Please add this as a good replacement of Animixplay, Also if possible add studio name and latest Button.

Thanks to the staff for this wonderful app

**Comment by rollingmoai** [comment]
Duplicate of #400
