### ISSUE TITLE
Miniop*ai

### ISSUE THREAD

**Issue by Start38** [jmir1/aniyomi-extensions#1122]
### Source information and language

Minioppai 13.3 (Indonesian/Indonesia)

### Steps to reproduce

1.Open the Minioppai extension 
2.Extension Displays Reading "No Result Found 
3.Already Saca Open with Webview But Website No Error

### Expected behavior

Should Show Anime 

### Actual behavior

Does Not Feature Any Anime

### Aniyomi version

0.13.5

### Android version

11

### Other details

![Screenshot_2022_1229_104717](https://user-images.githubusercontent.com/120931895/209901394-fa5f527f-56cd-4bda-87e5-a0beba38ec61.jpg)
![IMG_20221229_104839](https://user-images.githubusercontent.com/120931895/209901398-e6a343b1-3ff9-4154-9827-ae2a9fba9214.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Start38** [comment]
Please Repair Immediately

**Comment by hexated** [comment]
> Please Repair Immediately 

We don't have any dev for maintaining indo source anymore...

**Comment by Start38** [comment]
> > Mohon Segera Diperbaiki
> 
> Kami tidak memiliki dev untuk memelihara sumber indo lagi ...



> > Mohon Segera Diperbaiki
> 
> Kami tidak memiliki dev untuk memelihara sumber indo lagi ...

🥲

**Comment by DemuraAIdev** [comment]
oh no
