### ISSUE TITLE
Kamyroll: fix full state

### ISSUE THREAD

**Issue by Gtbita** [jmir1/aniyomi-extensions#1154]
### Source information and language

Kamyroll 13.6 (all)

### Steps to reproduce

The animes in release are in the complete state 

### Expected behavior

Animes in release should have status in progress

### Actual behavior

Animes in release are in full status 

### Aniyomi version

0.14.2.0-5863 (standard, 45d2af017, 93, 2023-01-07T02:26Z)

### Android version

Android 9 (SDK 28)

### Other details

this problem interferes with updating library items

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Samfun75** [comment]
The source doesn't provide the status of the anime so it is completed by default to prevent unnecessary traffic. There "might" be a feature coming that is beneficial to global updates or might not
