### ISSUE TITLE
[Feature Request] Kamyroll: German Dub/Sub

### ISSUE THREAD

**Issue by fscorrupt** [jmir1/aniyomi-extensions#1160]
it would be great if you had German dub/sub as an option to choose from for the prefered language under settings!

**Comment by Samfun75** [comment]
It's already there but the source identify it as de-De so in the extension setting set it as Dutch. If you're selecting from the player quality selection it is Aud: Dutch for audio and de-DE for hardsubs

**Comment by fscorrupt** [comment]
ah okey, maybe a different name should be chosen, Dutch is spoken in Nederland and its not german 😁 but thanks, now i know!

Rg

**Comment by Samfun75** [comment]
🤷‍♂️

![Screenshot (5)](https://user-images.githubusercontent.com/38332931/212255996-c0f6c2a6-ef31-4428-a948-4d93bb839940.png)

**Comment by fscorrupt** [comment]
Damn.. okey made an Issue on their Wiki page too! :D
