### ISSUE TITLE
[Feature Request] <GogoAnime>: <Request to bring back Gogostream>

### ISSUE THREAD

**Issue by Cistmist** [jmir1/aniyomi-extensions#1206]
Would like to request to bring back the Gogostream server since the StreamSD mostly has 480p and up, and Doodstream is 1080p.

The reason for this request is most of the time I used the app to download anime on the phone and the higher qualities are too big. So 360p was the go to always but now it's gone which was only available on the Gogostream server.

**Comment by Cistmist** [comment]
Adding that downloading from StreamSD returns Errors so the only server that can be downloaded from at the moment is Doodsteam.

**Comment by Heeseung-ah** [comment]
> Adding that downloading from StreamSD returns Errors so the only server that can be downloaded from at the moment is Doodsteam.

![Uploading Screenshot_2023-01-24-09-59-50-480_xyz.jmir.tachiyomi.mi.jpg…]()
![Uploading Screenshot_2023-01-24-09-59-01-603_xyz.jmir.tachiyomi.mi.jpg…]()

**Comment by Heeseung-ah** [comment]
> Adding that downloading from StreamSD returns Errors so the only server that can be downloaded from at the moment is Doodsteam.

![Uploading Screenshot_2023-01-24-09-59-50-480_xyz.jmir.tachiyomi.mi.jpg…]()
![Uploading Screenshot_2023-01-24-09-59-01-603_xyz.jmir.tachiyomi.mi.jpg…]()

**Comment by Cistmist** [comment]
Gogostream seems to be back so I'll close this.
