### ISSUE TITLE
[Bug] <kamyroll>: <failed conect>

### ISSUE THREAD

**Issue by Gtbita** [jmir1/aniyomi-extensions#1210]
![Screenshot_20230125-141048.png](https://user-images.githubusercontent.com/108306104/214632693-f676e89a-5790-4eb7-a145-38bce2dd147a.png)

This text is displayed when I enter the extension

**Comment by Secozzi** [comment]
Kamyroll got a DMCA notice and is shut down

**Comment by venkat2305** [comment]
Please add crunchyroll from consumet api

**Comment by venkat2305** [comment]
@Gtbita why did you close the issue? Please reopen this

**Comment by Secozzi** [comment]
What's the point of reopening? Kamyroll isn't coming back

**Comment by venkat2305** [comment]
I requested crunchyroll from Consumet api above. They might look into it if it's open
