### ISSUE TITLE
Problems when searching series in Vizer.tv

### ISSUE THREAD

**Issue by PHBN2021** [jmir1/aniyomi-extensions#1300]
### Source information and language

Vizer.tv 13.5 (Portuguese (Brazil))

### Steps to reproduce

1.Open the extension Vizier.tv
2.Filter by series, movies or anime and search by name
3. When I put the name of the series it only search certain words,like if I search "Lei & Ordem" doesn't appear anything but if I search "Lei" the series "Lei & Ordem: Unidade de Vítimas Especiais" appear and many other who don't have this words on title, and if I search "South" no series appear in the extension but if I search "park" series like "South Park" and others appear s even id they have no relation with the word searches

### Expected behavior

"Series with the respective words searched should appear"

### Actual behavior

"When search some times no series appear, and some time series even with no relation with the words searched appear

### Aniyomi version

0.12.3.10

### Android version

Android 12 S

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Claudemirovsky** [comment]
About the first example, this is not a problem in the extension, but in the source: You can do the same search [here](https://vizer.tv/series/online), and the same thing will happen.
About the second one, it really shouldn't happen, I'll fix it soon.
