### ISSUE TITLE
About Yomiroll's Demon Slayer

### ISSUE THREAD

**Issue by katagirii** [jmir1/aniyomi-extensions#1345]
### Source information and language

Yomiroll 13.17

### Steps to reproduce

When opening saved Demon Slayer Series from Yomiroll source, I see that Season 2 "Mugen Train Arc" and Season 3 "Entertainment District Arc" have their episodes collapsed with each other. From Season 2 Episode 1 to 7 is the "Mugen Train Arc" and Season 2 Episode 8 to 11 is the "Red Light District Arc". There are no Episodes 1 to 7 of "Red Light District" Arc. It's overlapped with each other it seems.

### Expected behavior

 Mentioned above

### Actual behavior

Mentioned above

### Aniyomi version

0.12.3.10

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Samfun75** [comment]
Entertainment District Arc is not season 3 hence crunchy sends the data of "Mugen Train Arc" and "Entertainment District Arc" as season 2 it's crunchy's fault. but I thought the "Entertainment District Arc" 1-7 is just the movie with some minor touchups.

**Comment by katagirii** [comment]
> Entertainment District Arc is not season 3 hence crunchy sends the data of "Mugen Train Arc" and "Entertainment District Arc" as season 2 it's crunchy's fault. but I thought the "Entertainment District Arc" 1-7 is just the movie with some minor touchups.

Ohk. Well the problem is resolved now so I will be closing it.
