### ISSUE TITLE
yomiroll not working 😭😭😭

### ISSUE THREAD

**Issue by RuDru-OP** [jmir1/aniyomi-extensions#1376]
### Source information and language

The extension is not working It says couldn't find video link 😭

### Steps to reproduce

Install Yomi roll extension
and try opening it.
It doesn't work as it used to.

### Expected behavior

it should show all anime on the homepage

### Actual behavior

shows connection timed out

### Aniyomi version

Latest version

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by JeyEmRS** [comment]
Sameee, I really like that extension since we it has the official subtitle (well it's *crunchy* after all).

**Comment by hvroun1** [comment]
Nice, since its working you should close this issue.
