### ISSUE TITLE
Keep getting this error after updating extension 

### ISSUE THREAD

**Issue by Helpful-Neko** [jmir1/aniyomi-extensions#1379]
### Source information and language

9anime  Version: 13.34  Language: English eu.kanade.tachiyomi.animeextension.en.nineanime

### Steps to reproduce

Try to use the 9anime extension. 

Downloads fail and fail to stream series on 9anime. 

### Expected behavior

Streaming anime and downloading anime.

It was working shortly after I updated  it. I downloaded the series toradora but then it suddenly stopped working. 

### Actual behavior

No streaming anime and no downloading anime. 

Attached image of error in the other details. 

### Aniyomi version

App version: 0.12.3.10 

### Android version

Android version: 11 

### Other details

![IMG_20230312_114119_162](https://user-images.githubusercontent.com/126541816/224555601-b8cd32de-54e1-4cfd-931e-b7c2b2119e6e.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ridoy829** [comment]
It's not working here too, once i updated its showing http error 500
