### ISSUE TITLE
[Source Request] Nyaa.si

### ISSUE THREAD

**Issue by Relwi** [jmir1/aniyomi-extensions#138]
## Source website
- Name: Nyaa.si
- Link: https://nyaa.si
- Language(s): All

## Other details
Only want to know if this source can be possible to add, I'm not expert in programming and may be legal problems with torrenting videos or that will need to use a VPN, etc...

If this source if possible to add, it could get the anime covers from https://anilist.co, https://kitsu.io or some other site? Since Nyaa doesn't have covers images. And getting the anime links from trusted uploaders? Since Nyaa has a lot of sources.

Or another option could be to add separate extensions for the trusted uploaders? Like SubPlease (https://subsplease.org), Erai-raws (https://www.erai-raws.info), etc...

**Comment by MoonLGH** [comment]
We dont need vpn ?, we can use inbuilt tachiyomi 1.1.1.1 ?

**Comment by MoonLGH** [comment]
https://github.com/manga-download/hakuneko/issues/3049

I dont think its a good idea then 😳

**Comment by MoonLGH** [comment]
https://sourceforge.net/projects/bitext/
You can use these though
