### ISSUE TITLE
9anime: HTTP error 500 when fetching anime details

### ISSUE THREAD

**Issue by mklive** [jmir1/aniyomi-extensions#1384]
### Source information and language

9anime 13.35 (English)

### Steps to reproduce

Go to 9anime latest series.
Tap on an anime

### Expected behavior

It should populate a series with episodes

### Actual behavior

Pops up HttpException: HTTP error 500

### Aniyomi version

Beta r6135

### Android version

Android 11

### Other details

I suspect it's because consumet API is unstable and it will give server errors

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Nintenstation** [comment]
Yes, I'm having this exact issue. Emphasizing this!

**Comment by nine-anime** [comment]
@jmir1 
We don't like to be an app extension, so please stop to not waste your time.

**Comment by jmir1** [comment]
> @jmir1 
> We don't like to be an app extension, so please stop to not waste your time.
> 

Yo what's up, is this the real 9anime?
Your website sucks

**Comment by nine-anime** [comment]
Yes, we're.
Your app too bro, it seems hard to run without our site.

**Comment by nine-anime** [comment]
Of course, if he didn't say that. We just want to talk peacefully.
If you feel that's funny.... Take your time.

**Comment by jmir1** [comment]
@nine-anime 
Your website does not have any terms and conditions or anything that says we cannot fetch data from your website.
It does state however, that you are only linking to content from third parties, so why shouldn't we be allowed to do the same?

**Comment by nine-anime** [comment]
The point is your app use our server resources, we don’t want to be flooded without any benefits, no new user, no visitor, just more resource usage.

We do not want to waste our time on cat and mice game, so we’re here. Of course, if you don’t agree, we can play until one stopped like Saiko.

**Comment by jmir1** [comment]
Locking this because the discussion has nothing to do with this issue
