### ISSUE TITLE
Still getting error after 9anime extension update 

### ISSUE THREAD

**Issue by Helpful-Neko** [jmir1/aniyomi-extensions#1392]
### Source information and language

Version: 13.36  Language: English eu.kanade.tachiyomi.animeextension.en.nineanime

### Steps to reproduce

Try to use the 9anime extension.

### Expected behavior

Open 9anime anime series for streaming and download 

### Actual behavior

Fails to even bring up anime episode list.

### Aniyomi version

App version: 0.12.3.10 

### Android version

Android 11

### Other details

App version: 0.12.3.10 (standard, 7722361, 72, 2023-02-09T10:47Z)
Android version: 11 (SDK 30)
Device brand: Motorola
Device manufacturer: Motorola 
Device model: moto g power (2020)
Device product name: sofia_retail

![Screenshot_20230314-095942-698](https://user-images.githubusercontent.com/126541816/225028252-b4f6b280-721f-4cff-a39c-309150faf02a.png)

9Anime extension version Version: 13.36
Language: English eu.kanade.tachiyomi.animeextension.en.nineanime

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by 2067manishkulkarni** [comment]
I'm also having the same problem with gogoanime as weel as 9anime maybe all anime sources are not working I can't watch even any anime from the extensions

**Comment by Helpful-Neko** [comment]
This was fixed by clearing data, system cash, and using a beta version of the app
