### ISSUE TITLE
Source request mangafire.to

### ISSUE THREAD

**Issue by Helpful-Neko** [jmir1/aniyomi-extensions#1465]
### Source name

mangafire.to

### Source link

https://mangafire.to/home

### Language

All

### Other details

NSFW/Yes 
![224132621-e9af04dc-1525-40c8-b336-309780167220](https://user-images.githubusercontent.com/126541816/229954649-52c982c1-44c7-4712-a5f4-946766afc2e5.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/jmir1/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Manga extensions request goes to the tachiyomi github, but since there already exists [a request for it](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/15370), there's no need to send one there

**Comment by Helpful-Neko** [comment]
> Manga extensions request goes to the tachiyomi github, but since there already exists [a request for it](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/15370), there's no need to send one there

Oh I didn't know I'll close this issue then. I was going to try to make the extension myself but realized I didn't exactly understand how 😅

**Comment by Secozzi** [comment]
You can close it, since no manga extentension are managed on this repo

**Comment by Helpful-Neko** [comment]
> You can close it, since no manga extentension are managed on this repo

Thank you for letting me know 😸
