### ISSUE TITLE
Yomiroll problem episode not found

### ISSUE THREAD

**Issue by Gtbita** [jmir1/aniyomi-extensions#1492]
### Source information and language

Yomiroll 13.20 (All)

### Steps to reproduce

I select an anime in the extension waiting for the episodes to appear, but instead it just shows the message "Episode not found".

### Expected behavior

The list of episodes should appear

### Actual behavior

The episode list does not appear

### Aniyomi version

Preview 0.14.3-6145

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by toomyzoom** [comment]
Seem like refresh token expired. It shows as non-premium.
