### ISSUE TITLE
[Bug] <neonime>: <can't streaming>

### ISSUE THREAD

**Issue by exaltedme7** [jmir1/aniyomi-extensions#156]
![Screenshot_2021-11-12-21-05-29-171_xyz jmir tachiyomi mi debug](https://user-images.githubusercontent.com/58416568/141479908-c153c45f-6fd1-441f-a5d0-122f20693128.png)

One piece error bug

**Comment by JoshBot-Debug** [comment]
Which plugin are you using?

**Comment by dm699** [comment]
NeoNime? I can't see that extension in the downloads
