### ISSUE TITLE
Gogoanime GogoStream 403 error only on new anime

### ISSUE THREAD

**Issue by Cistmist** [jmir1/aniyomi-extensions#1645]
### Source information and language

Gogoanime 13.62

### Steps to reproduce

Open any video.
Check Video Quality.

### Expected behavior

Be able to choose Gogostream as it was the only server that allowed Downloads in different qualities (StreamSD gives back errors when downloading)

### Actual behavior

The Gogostream options aren't there and can't download except on Doodstream.

Opened a similar post in the past #1206 which I closed when it was fixed.

### Aniyomi version

0.12.3.10

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Imon24** [comment]
In gogoanime 13.63 I'm still facing the problem

**Comment by Cistmist** [comment]
Yup same

**Comment by givemyusd** [comment]
in gogoanime site they have changed embed url of video. the updated url is https://gotaku1.com/streaming.php?id=filename .this url should be updated in extracter

**Comment by Cistmist** [comment]
Extension is broken again. Yesterday it was fixed after updating.

![Screenshot_20230531-200036](https://github.com/jmir1/aniyomi-extensions/assets/49917604/057b9859-194f-43ea-8238-e830f7ad6189)

**Comment by Cistmist** [comment]
@jmir1 can you reopen the thread? As a new issue appeared after it was fixed yesterday.

**Comment by Cistmist** [comment]
Noticed that only newer anime have the problem above. While older ones work fine.
