### ISSUE TITLE
[Bug] Episodes won't load because of the episode name.

### ISSUE THREAD

**Issue by NJD135** [jmir1/aniyomi-extensions#17]
## Device information
* Tachiyomi version: 0.11.1.5-mi-3686
* Android version: 10
* Device: Xiaomi redmi note 7 pro

## Steps to reproduce
1. Go to 4anime.to extension and search re:zero
2. Select the first season and open it.

### Expected behavior
Since all the episodes are available on the website, the episodes should appear on Aniyomi.

### Actual behavior
The episodes doesn't appear and give the error : For input string:"01A".

## Other details
The first and second episodes of the show in the website is named as 01A and 01B  respectively.

**Comment by jmir1** [comment]
Closing cause 4anime is deprecated
