### ISSUE TITLE
[Bug] <AnimeFLV>: <Couldn't find any video links>

### ISSUE THREAD

**Issue by Yzakrio** [jmir1/aniyomi-extensions#178]
## Device information
- Tachiyomi version: 0.12.3.5
- Android version: 11

## Source information
- Name: AnimeFLV
- Extension version: 12.3

## Steps to reproduce
1. First Step, Open the source (AnimeFLV)
2. Second Step, Open, for example: Ousama Ranking -> Episodio 1 

### Expected behavior
Anime should be played.

### Actual behavior
Anime doesn't play and you get the following error message:
![260306751_957606614836268_1436920375729603444_n](https://user-images.githubusercontent.com/95396802/144726493-0e2868cc-68d8-467a-9bfc-7a672413d8f3.jpg)

## Other details
There was an issue opened before with this same bug ( #117), but it was on Aniyomi 0.12.3.1 and same extension version, just wanted to say the bug its still there.

**Comment by franklin2457** [comment]
For left or now a week gogoanime no links

**Comment by franklin2457** [comment]
For like a week now I have been facing issues of video links on gogoanime
and other problems like HTTP error on animepache I hope for a resolution
soon.thank You.

**Comment by franklin2457** [comment]
How do l use the streamtape extractor on aniyomi

**Comment by jmir1** [comment]
please stop commenting unrelated things on this issue.


> How do l use the streamtape extractor on aniyomi


to answer your question, you don't *use* it at all, you just click the episode and select the streamtape video quality if it is available.
