### ISSUE TITLE
[Bug] Oploverz : failed to parse some of zippyshare links

### ISSUE THREAD

**Issue by MoonLGH** [jmir1/aniyomi-extensions#189]
**PLEASE READ THIS**

I acknowledge that:
---

## Device information
- Tachiyomi version: v0.12.3.5
- Android version: 11

## Source information
- Name: Oploverz
- Extension version: 5

## Steps to reproduce
1. Go to oploverz
2. seach kimetsu no yaiba, and pick the mugen rennsha

### Expected behavior
parsing the zippyshare link

### Actual behavior
Describe what happens instead
didnt parse the zippyshare link

## Other details
kimetsu eps 1 https://oploverz.fan/kimetsu-no-yaiba-mugen-ressha-hen-episode-01-subtitle-indonesia/#
with zippyshare link https://www76.zippyshare.com/v/azvLOUZu/file.html
failed to parse

but, with otakudesu
https://otakudesu.vip/shinkanomi-episode-11-sub-indo/
with zippyshare link https://www26.zippyshare.com/v/T3lKGNg2/file.html
it success to parse

**Comment by jmir1** [comment]
I'm not exactly sure what on the website caused this but now i just filtered out the links that returned an error.
