### ISSUE TITLE
[Bug] <all Arabic sources>: <can't play any anime>

### ISSUE THREAD

**Issue by Mua10** [jmir1/aniyomi-extensions#193]
![145840465-eefa0138-1822-4291-ab35-1c6f08e1d669](https://user-images.githubusercontent.com/95976690/146166740-00d5b8cc-7248-4de5-8abd-511c57432eff.png)

---

## Device information
- Tachiyomi version:0.12.3.5
- Android version: 8.1.0

## Source information
- Name:all
- Extension version:latest

## Steps to reproduce
1.enter any source
2.play any episode

### Expected behavior
It should be playing the anime as usual

### Actual behavior
But it is not actually playing and it keeps crashing

**Comment by jmir1** [comment]
it appears the issue is on your end. try using a vpn or switch to another source.
