### ISSUE TITLE
[BUG] Hanime extension : episodes are seen as whole series

### ISSUE THREAD

**Issue by castrik** [jmir1/aniyomi-extensions#20]
I opened an issue here since its related to an extension not officially supported by tachiyomi
 
## Device information
- Tachiyomi version: all versions
- Android version: 11

## Source information
- Name: Hanime
- Extension version: 11.6

## Steps to reproduce
1. just open it

### Expected behavior
Describe what should have happened

series should be shown individually and all episodes should be in a series, its ok if it is divided by different seasons

### Actual behavior
Describe what happens instead

all episodes are shown as individual series and when we go in episode list, it just shows as single episodes

### Other information

here are a few screenshots (censored)
![20210616_182054](https://user-images.githubusercontent.com/84063610/122223699-3d7ead00-ced5-11eb-9e80-fd863ebcec50.jpg)
![20210616_182340](https://user-images.githubusercontent.com/84063610/122223793-55563100-ced5-11eb-9b58-b5cae1c37ced.jpg)

**Comment by castrik** [comment]
well, the website does show next episodes under the current playing one, maybe they have some system for it?

**Comment by jmir1** [comment]
closing since this will not be fixed.
