### ISSUE TITLE
[Source Request] <mangareader.to>

### ISSUE THREAD

**Issue by shakibkirito** [jmir1/aniyomi-extensions#215]
## Source website
- Name: mangareader.to
- Link: https://mangareader.to/
- Language(s): en

## Other details
It's an website developed by the creators of zoro.to

**Comment by 12345axc** [comment]
All of manga extension is handled by Tachiyomi, not Aniyomi.
Please make a request on Tachiyomi extension repo for next request or bug report: https://github.com/tachiyomiorg/tachiyomi-extensions

Also, there is already a request on Tachiyomi for Mangareader: https://github.com/tachiyomiorg/tachiyomi-extensions/issues/9112
