### ISSUE TITLE
Add animepahe as extension

### ISSUE THREAD

**Issue by raffyOmega** [jmir1/aniyomi-extensions#22]
Hello admin, can you add animepahe  extension? Cause it is one of the best sites to watch and there is a quality selection , the 720,1080 both compressed size compare to 4anime and the existing extension you add ,  and my issue is that i have only 16gb of internal storage ,thanks for making this kind of app..

**Comment by Rei240** [comment]
Yes,you are absolutely right. I also like this website.

**Comment by jmir1** [comment]
closing cause AP is already added
