### ISSUE TITLE
[Bug] Anitube: does not show up as anime source after installed

### ISSUE THREAD

**Issue by felipecrs** [jmir1/aniyomi-extensions#241]
## Device information
- Tachiyomi version: 0.12.3.6
- Android version: 12

## Source information
- Name: Anitube
- Extension version: 12.1

## Steps to reproduce
1. Install Anitube extension (currently version is 12.1)
2. Notice that it does not show up in Anime sources as other extensions do

### Expected behavior
I believe it was supposed to show up there so I could watch animes from it.

### Actual behavior
It does not show up in anime sources.

## Other details
I'm new to Aniyomi. Perhaps I'm doing or expecting something wrong?

**Comment by 12345axc** [comment]
On Anime Extensions, you should enable `Português` language option.
The button is on the top right.

**Comment by felipecrs** [comment]
It was already enabled, check the video:

https://user-images.githubusercontent.com/29582865/149774187-3f7c6b3f-0a40-4c01-bbbe-bf7f7e978db2.mp4

**Comment by jmir1** [comment]
@felipecrs you need to enable pt-br language in the "Anime Sources" tab, not "Anime Extensions".

**Comment by felipecrs** [comment]
Wow thanks a lot. Now it works!
