### ISSUE TITLE
[Bug] <Dramacool>: <Dramacool not working with external video player>

### ISSUE THREAD

**Issue by RaKeerS** [jmir1/aniyomi-extensions#303]
## Device information
- Tachiyomi version: 0.12.3.6
- Android version: 12

## Source information
- Name: Dramacool
- Extension version: 12.2

## Steps to reproduce
1. Select any series in Dramacool with External Player option set to on (No default external player set)
2. The app automatically chooses VLC as it's default player (even if I have MX player and default video player installed.)

### Expected behavior
The selected episode should play properly on the external player

### Actual behavior
The episode doesn't play even if it selects VLC as it default external player (which I haven't selected in the settings)

The following error is shown, similar to my previously reported bug of AsianLoad extension - #269

It throws a similar error as shown in the image underneath - 

![Screenshot_20220205-214035_Aniyomi.jpg](https://user-images.githubusercontent.com/22376097/152649364-986c6134-60a0-4750-aaec-1667baa1dd4a.jpg)

**Comment by ahmedgamal17** [comment]
Ok so it's not extension problem or app problem it's video player problem so close this issue

**Comment by RaKeerS** [comment]
I don't think so, as with the previous version it was working correctly. Also, there seems to be some issue with the app too, as for some extensions it shows me a list of all my installed video players but for this extension (post update to 12.2) it doesn't show me a list of all my installed video players [I have a default video player, 2 extra video players, since no default video player is mentioned in app settings]. Previously, in the version before 12.2 for the extension, it used to show me a list of all installed video players to select one of them for playback.
