### ISSUE TITLE
[Bug] IsekaiScan.com: Not working anymore

### ISSUE THREAD

**Issue by MatisPrograms** [jmir1/aniyomi-extensions#339]
## Device information
- Tachiyomi version: 0.12.3.6
- Android version: 11

## Source information
- Name: IsekaiScan.com
- Extension version: 1.2.19

## Steps to reproduce
1. Open any manga using IsekaiScan or browse any manga

### Expected behavior
It should of open the managa like with any other extensions

### Actual behavior
It loads for some time (untill its timeout) and then stops and go back to previous page.

## Other details
Recently the hole website was down (for several days) and when it went back online it became impossible to use the IsekaiScan.com extension du to probably changes that was done to the website (maybe more security)

**Comment by ahmedgamal17** [comment]
No manga support here go to tachiyomi-extensions repo

**Comment by MatisPrograms** [comment]
Oups I forgot aniyomi was the anime fork... 😅

**Comment by ahmedgamal17** [comment]
So you can close it now
