### ISSUE TITLE
[Source Request] <f1livegp.me>

### ISSUE THREAD

**Issue by rohan2000github** [jmir1/aniyomi-extensions#361]
## Source website
- Name: f1livegp.me
- Link: https://f1livegp.me/f1/live3.html
- Language(s): English

## Other details
This website live streams F1 races. Is it possible to add this as an extension to aniyomi ? @jmir1

**Comment by jmir1** [comment]
it is possible, but this type of extension will not be in this repository, as the main purpose of the app is anime and manga :)
