### ISSUE TITLE
Adding spanish audio option on anime flv extension

### ISSUE THREAD

**Issue by Sebas365** [jmir1/aniyomi-extensions#366]
---

## What feature should be added to this source?
Explain why this should be added

Well, as an spanish anime page, anime flv has the option to choose between japanese audio or spanish dub on the anime that support it, i though it would be great to have that option added on anime flv extension.

**Comment by Sebas365** [comment]
That's not what i meant

**Comment by jmir1** [comment]
sorry closed the wrong issue.

**Comment by Diegopyl1209** [comment]
ok, esta semana tal vez lo haga o este mes nose

**Comment by Diegopyl1209** [comment]
Bueno, acabo de revisar y no encontré ningún anime que tuviera la opción para verlo con el audio original o doblado, recuerdo que si existía pero no se si la abran eliminado

**Comment by Sebas365** [comment]
Busqué y encontré algunos que poseen la opción como maid dragon, naruto, naruto shippuden, back street girls, one punch man, re: zero temporada 1, fullmetal alchemist brotherhood

**Comment by Diegopyl1209** [comment]
> Busqué y encontré algunos que poseen la opción como maid dragon, naruto, naruto shippuden, back street girls, one punch man, re: zero temporada 1, fullmetal alchemist brotherhood

gracias por responder, pronto veras una actualización de la extensión, los animes que tienen la opcion para verlo con doblaje en el apartado de la calidad aparecerá como "DUB: SERVER" puedes probarlo con la primera temporada de "kobayashi-san", esta opción solo soporta los server "Okru" y "Fembed" asi que si fueron removidos por copyright no aparecerán
