### ISSUE TITLE
[Extension Request] zoro.to

### ISSUE THREAD

**Issue by JahinAbrar** [jmir1/aniyomi-extensions#39]
As we know Aniyomi has 3 anime extensions but in my region only gogo anime is supporting however it is very slow and buffering alot ( I can assure u that its not a internet issue).So i would like the developers to add zoro.to as a extension in the future updates as it is a ad free and fast anime website which is getting alot of hype in the anime community lately.

Website link: https://zoro.to/

**Comment by jmir1** [comment]
has already been added.
