### ISSUE TITLE
[Source Request] <Kamyroll>

### ISSUE THREAD

**Issue by HitaloM** [jmir1/aniyomi-extensions#400]
---

## Source website
- Name: Kamyroll
- Link: https://github.com/hyugogirubato/Kamyroll-Developers
- Language(s): multi-lang

## Other details

I discovered a few days ago this project that facilitates the use of crunchyroll and funimation APIs with bypass support for free accounts, it would be a great extension considering there is support for multiple langs (dubs and subs).

**Comment by rollingmoai** [comment]
API: https://api.kamyroll.tech/
Wiki: https://github.com/kamyroll/Kamyroll-Wiki
