### ISSUE TITLE
[Bug] <Gogoanime> extension quality issues

### ISSUE THREAD

**Issue by Cistmist** [jmir1/aniyomi-extensions#428]
## Device information
* Tachiyomi version: 0.13.1
* Android version: 11
* Device: ?

## Source information
* Source name: gogoanime
* Source extension version: 12.33

## Issue/Request
- Error 500 when trying to play a video.
- Checking the quality has <\centerp> as a result.
- Extension settings and player have different quality settings.
- Player defaults to 1080p always regardless of what you choose in the quality.

**Comment by jmir1** [comment]
can you tell me which exact anime and episode causes this problem?

**Comment by jmir1** [comment]
> Player defaults to 1080p always regardless of what you choose in the quality.

this is normal btw. some newer episodes on gogoanime have 270p instead of 360p so it will default to 1080p if you have 360p in the settings.

**Comment by Cistmist** [comment]
> > Error 500 when trying to play a video.
> > Checking the quality has <\centerp> as a result.
> 
> can you tell me which exact anime and episode causes these problems?

Toaru no majutsu index 2 episode 14 is the one I noticed the error on. Checked a couple other episodes in the same but seems ep 14 is messed up?.

**Comment by Cistmist** [comment]
> > Player defaults to 1080p always regardless of what you choose in the quality.
> 
> this is normal btw. some newer episodes on gogoanime have 270p instead of 360p so it will default to 1080p if you have 360p in the settings.

Good to know. Though that's not what I meant, by player I meant when you open an episode and try to change the quality, it stayed the same (especially on the latest anime). 

Tried checking with a limited connection to test it out and the amount of mb spent was the same when I kept it at 1080 or when I played it at 480.
