### ISSUE TITLE
[Source Request] Exhentai

### ISSUE THREAD

**Issue by Josephl64** [jmir1/aniyomi-extensions#43]
https://exhentai.org/
- Name: Exhentai
- Link: https://exhentai.org/
- Language(s): English, Japanese, Spanish, Korean, etc.

I have been using Aniyomi and absolutely love it, but I still have to use other apps like TachiyomiAZ whenever I want to access the site. It encompasses more material than the regular E-Hentai extension which already exists on Aniyomi.  Would be very helpful if this could get added as well. 

Thanks for your time.

**Comment by jmir1** [comment]
Closing cause not an anime source
