### ISSUE TITLE
[Feature Request] <Gateanime Cima4u Cima4up GateCima>: <New Arabic Anime Sites>

### ISSUE THREAD

**Issue by NORDINOHDDA** [jmir1/aniyomi-extensions#440]
Name: Gateanime
Link: https://s.gateanime.com
Language: Arabic / العربية

Name: Cima4u
Link: https://cima4u.film
Language: Arabic / العربية

Name: Cima4up
Link: https://cinema4up.net
Language: Arabic / العربية

Name: gatecima
Link: https://gatecima.com
Language: Arabic / العربية

**Comment by jmir1** [comment]
same as #433

**Comment by jmir1** [comment]
thats not how this works my firiend 😂
