### ISSUE TITLE
[Source Request] 9anime

### ISSUE THREAD

**Issue by mnabid** [jmir1/aniyomi-extensions#46]
## Source website
- Name: 9anime
- Link: 
`https://9anime.to` (original)
`https://9anime.me` (official mirror list)
- Language(s): English, Japanese

**Comment by SaqinNoor** [comment]
I want this too!!!!!!!!!

**Comment by Aceiow** [comment]
### Use Animekisa
They have added Animekisa . There are .tv and .in . tv scrapes from gogo and .in scrapes from 9anime afaik . The version that we have is .in so you can say we have 9anime . Just give it a try .

**Comment by mnabid** [comment]
Yup, I do use it as my go-to extension.
But I'm keeping this PR open anyway since there are some problems with AnimeKisa―

 - **It only scrapes Vidstream and Mycloud**
   No Videovard/Streamtape/Mp4upload.
 - **The search function is a mess**
   Search *"My Hero Academia"* and see what I'm talking about.
 - **New episodes show up long after 9anime uploads them**
    Probably because [AnimeKisa doesn't want to get DDoS'd](https://torrentfreak.com/massive-pirate-anime-site-uses-visitors-connections-to-ddos-competitor-201014/) ¯\\\_(ツ)\_/¯

**Comment by SaqinNoor** [comment]
Thank you for your comment. I have recently switched from watching anime on
mobile to PC so i dont use aniyomi that much anymore. But if i use aniyomi
agan, i'll definitely try AnimeKisa.

**Comment by jmir1** [comment]
Done with ea9bea76f82d13dc1ce28654ffe4e94835396fd6
