### ISSUE TITLE
[Bug] Animeworld.tv: "open in app" doesn't detect the extension

### ISSUE THREAD

**Issue by Palloxin** [jmir1/aniyomi-extensions#466]
## Device information
- Tachiyomi version: r4507
- Android version: android 8

## Source information
- Name: Anineword.tv
- Extension version: 12.6

## Steps to reproduce
1. visit the website animeworld.tv on a browser with the extension installed on the phone
2. look for the option "open in app" in that browser 

### Expected behavior
Tge option "open in app" should appear on the browser

### Actual behavior
The option "open in app" doesn't appear

## Other details
i tried with Hiperdex (a manga extension) and it does detect aniyomi (extension of hiperdex already installed).
![IMG_20220406_125249](https://user-images.githubusercontent.com/75091899/161960831-2d2c6de4-bd4e-430b-9dc2-0c209698a869.jpg)

**Comment by Claudemirovsky** [comment]
It's not a bug, the animeworld.tv extension doesn't have the function to open external urls, but Hiperdex does.
