### ISSUE TITLE
[Feature Request] <Gogoanime>: <Is it possible to get the quality choices back?>

### ISSUE THREAD

**Issue by Cistmist** [jmir1/aniyomi-extensions#494]
The latest change to the Gogoanime extension quality names, being Autop and doodstream.

Is it possible to get the 360, 480, 1080 options back? 

Autop is weird as it keeps pausing sometimes during play (have to press the play button to resume), and doodstream is always 1080 (which is great) but having some of the lower qualities would be great.

**Comment by rohan2000github** [comment]
You can select the quality in the extension settings option.

**Comment by Cistmist** [comment]
> You can select the quality in the extension settings option.

I know, but if the option isn't available in the video it's a different matter no?

**Comment by Cistmist** [comment]
Though the latest extension update now changed the Autop option so will wait to see if that's actually it before I close this

**Comment by Cistmist** [comment]
Nvm, it's gone. Only doodstream is available.

**Comment by Manimdumb** [comment]
Yup am having same problem too and with the limited net it's being a lot annoying and it cuts and joins connection continuously as if like cut and join, cut and join.
It is annoying
Hope Gogoanime fixes this

**Comment by Manimdumb** [comment]
Now that they fixed it if we try to play in 720p or any other it won't load the video and will only work in doodstream mirror

**Comment by Cistmist** [comment]
> Now that they fixed it if we try to play in 720p or any other it won't load the video and will only work in doodstream mirror

It was fixed for a short while in the new update yeah, but when I checked the videos didn't have sounds on them and then a couple hours later they disappeared. 

My guess it's something from gogo, so this forces them to update to code constantly.

**Comment by Cistmist** [comment]
Thanks jmir as always!
