### ISSUE TITLE
[Bug] <Pelisplus>: <erroneous domain of pelisplus>

### ISSUE THREAD

**Issue by sechs47** [jmir1/aniyomi-extensions#497]
## Device information
- Tachiyomi version: 0.12.3.6
- Android version: 11

## Source information
- Name: pelisplushd
- Extension version: last

## Steps to reproduce
1 .error in the content
2. the domain is incorrect

### Expected behavior
use the original page

### Actual behavior
the domain using the extension is wrong, the real domain is .nu

## Other details
the domain that uses the extension is .lat but the original page of pelisplus uses the domain .nu, therefore many anime, series... are not reproduced, because the page is a clone of the original.
![image](https://user-images.githubusercontent.com/103461300/163279410-622af27c-19cc-4a9b-911b-7e5b4dc92c07.png)

**Comment by jmir1** [comment]
closed by 13c874f80b412757632a8ce1d0ece8e0be9c2c7b
