### ISSUE TITLE
[Source Request] any Polish extension

### ISSUE THREAD

**Issue by kenhubv50** [jmir1/aniyomi-extensions#504]
Could you add any Polish extensions? Maybe something from websites supported by MAL-Sync: desuonline, animeodcinki, shinden, animezone, frixysubs, fumetsu

## Source website 1
- Name: desu-online
- Link: https://desu-online.pl
- Language(s): Polish

## Source website 2
- Name: anime-odcinki
- Link: https://anime-odcinki.pl
- Language(s): Polish

## Source website 3
- Name: shinden
- Link: https://shinden.pl
- Language(s): Polish

## Source website 4
- Name: animezone
- Link: https://www.animezone.pl
- Language(s): Polish

## Source website 5
- Name: frixysubs
- Link: https://frixysubs.pl
- Language(s): Polish

## Source website 6
- Name: fumetsu
- Link: https://fumetsu.pl
- Language(s): Polish

**Comment by kenhubv50** [comment]
Any chance of adding any of these sources?

**Comment by jmir1** [comment]
yeah ok
