### ISSUE TITLE
[Bug] Gogoanime: missing link error

### ISSUE THREAD

**Issue by Cistmist** [jmir1/aniyomi-extensions#505]
## Device information
- Aniyomi version: 0.12.3.6
- Android version: 11

## Source information
- Name: gogoanime
- Extension version: 12.37

## Steps to reproduce
1. Play any video of the recently updated anime
2. Choose a quality other than doodstream

### Expected behavior
Have sound

### Actual behavior
No sound

**Comment by Cistmist** [comment]
Nvm the quality option are gone.
New anime are still playable with the doodstream quality. 
Meanwhile old ones like for example <A certain scientific index> return nothing but an error with a missing link upon trying to open a video.

**Comment by rohan2000github** [comment]
I think u should reopen this LoL.
