### ISSUE TITLE
[Bug] gogoanime.tv: cannot stream nor download

### ISSUE THREAD

**Issue by 69DUCKMYSICK69** [jmir1/aniyomi-extensions#52]
## Device information
- Tachiyomi version: 0.11.1.11
- Android version: 11

## Source information
- Name: gogoanime.tv 
- Extension version: 12.7

## Steps to reproduce
1. Open gogoanime.tv extension 
2. Click on an anime 
3. start en episode/download 

### Expected behavior
Start the episode/the download

### Actual behavior
Crashes the app/says the download failed list empty
[tachiyomi_crash_logs.txt](https://github.com/jmir1/aniyomi-extensions/files/6890015/tachiyomi_crash_logs.txt)

**Comment by jmir1** [comment]
fixed in a08850124902835c781edd21f2fe7047c0cb2216
