### ISSUE TITLE
[Source Request] <some Indonesian website>

### ISSUE THREAD

**Issue by bigbabyboost** [jmir1/aniyomi-extensions#522]
Otakudesu new site
        Name: Otakudesu
        Url:  https://otakudesu.site
      
        Name : Samehadaku
        url:  https://194.163.183.129

        Name:  Gatsunime
        Url : https://gatsunime.org
       
        Name : anoboy
        Url : ttps://anoboy.digital
       
        Name :  Anime-Indo
        Url : https://anime-indo.one"
        
  Oploverz new domain
        Name: Oploverz
        Url : https://oploverz.asia
     
        Name : LK21
        Url : https://149.56.24.226

**Comment by MoonLGH** [comment]
```
    Otakudesu new site
    Name: Otakudesu
    Url:  https://otakudesu.site
  
  Oploverz new domain
Name: Oploverz
Url : https://oploverz.asia/
```
if you use DNS over https, it would be fine and it will redirect to the new domain


but for safety let me update that

**Comment by MoonLGH** [comment]
That's negative, I'm Indonesian and seems like Cloudflare DoH can open otakudesu nicely.

**Comment by bigbabyboost** [comment]
> That's negative, I'm Indonesian and seems like Cloudflare DoH can open otakudesu nicely.

Are you using wifi? DNS seems works on wifi but no with cellular data
