### ISSUE TITLE
[Source Request] Türk Anime TV

### ISSUE THREAD

**Issue by Redbot19** [jmir1/aniyomi-extensions#56]
## Source website
- Name: Türk Anime TV
- Link: https://www.turkanime.net/
- Language(s): sub Turkish

**Comment by Redbot19** [comment]
😥

**Comment by kyoyacchi** [comment]
:/

**Comment by Redbot19** [comment]
😥

**Comment by Redbot19** [comment]
🤨

**Comment by Redbot19** [comment]
Bir senedir araliklarla bakiyorum inat ettim bekliyiom hâlen

**Comment by kyoyacchi** [comment]
Bizim sitelerin herkese açık API'si olmadığından veri çekmek uğraştırıcı oluyor sanırım. Gelmesi imkânsız diye düşünsem yeridir, biri çıkıp uğraşmadığı sürece.

Gelse de tarayıcı kullanmak zorunda kalmasam...

**Comment by jmir1** [comment]
fe53f7a8c1068739728d15a5c9d0b51b2b7c3353

**Comment by kyoyacchi** [comment]
@jmir1 Thank you.
