### ISSUE TITLE
[Bug] <9anime>: <Unable to Bypass Cloudflare>

### ISSUE THREAD

**Issue by sr-777** [jmir1/aniyomi-extensions#574]
## Device information
- Tachiyomi version: 0.12.3.5
- Android version: 9

## Source information
- Name: 9anime
- Extension version: latest

## Steps to reproduce
> Install and 9anime extension
> click on any tiles or try to search something

### Expected behavior
`episode should load and search should work`

### Actual behavior
![IMG_20220529_124614](https://user-images.githubusercontent.com/97355073/170856790-d7e3717d-2233-4a94-b478-2924999eb33c.jpg)
![IMG_20220529_124529](https://user-images.githubusercontent.com/97355073/170856794-a8432832-bdba-4508-9c74-594d490c66c0.jpg)

**Comment by jdyaras** [comment]
Hi, how've you been doing? I've noticed I'm getting this error too. I tried everything; first doing the troubleshooting guide (cloudflare, webview, diagnosis, checking updates, etc.), cleaning cache and rebooting, uninstalling the app and deleting residual files then reinstalling, and trying the preview release. Funny thing is I can open 9anime in webview, it doesn't even ask me for captcha or similar, but I still get the cloudflare error if I try to see an episode or load the episode list on the app afterwards. Have you found a solution for this problem?

**Comment by 12ohit** [comment]
@sr-777 This is not the cloud flare issue, the 9anime extension itself has problem wait until it gets fixed, until that you can do nothing to make it work

**Comment by Jcross1029** [comment]
HI having the same issue tried everything in the troubleshoot guide, currently using 1.2.4 of 9anime extension and still broke

**Comment by Jcross1029** [comment]
> Hi, how've you been doing? I've noticed I'm getting this error too. I tried everything; first doing the troubleshooting guide (cloudflare, webview, diagnosis, checking updates, etc.), cleaning cache and rebooting, uninstalling the app and deleting residual files then reinstalling, and trying the preview release. Funny thing is I can open 9anime in webview, it doesn't even ask me for captcha or similar, but I still get the cloudflare error if I try to see an episode or load the episode list on the app afterwards. Have you found a solution for this problem?
> 
> This is my device and app info: Tachiyomi version: 0.13.4 Aniyomi version: 0.12.3.6 Android version: 8
> 
> Source: Name: 9anime Extension version: 12.4

HI having the same issue tried everything in the troubleshoot guide, currently using 1.2.4 of 9anime extension and still broke

**Comment by jmir1** [comment]
should be fixed by now.
