### ISSUE TITLE
[Bug] 9Anime: "Failed to bypass Cloudflare" even though CAPTCHA doesn't show up in Webview.

### ISSUE THREAD

**Issue by Francisco576** [jmir1/aniyomi-extensions#577]
## Device information
-Aniyomi version: 0.12.3.6
- Android version: 12

## Source information
- Name: 9Anime
- Extension version: English 12.4

## Steps to reproduce
1. Install 9Anime
2. Open it
3. Choose an Anime
4. "Failed to bypass Cloudflare"
5. Open it in Webview

### Expected behavior
CAPTCHA should show up

### Actual behavior
CAPTCHA doesn't show up

## Other details
I've tried following the official guides and looking it up on youtube to see if i could fix it but i can't.

**Comment by Francisco576** [comment]
Couldn't see it earlier, but it appears there is an identical post to mine on here so i guess i have to wait till the extension itself is fixed.

**Comment by 12ohit** [comment]
@Francisco576 This is not captcha bypass problem, 9anime extension is broken, wait for someone to fix it

**Comment by jmir1** [comment]
is fixed.
