### ISSUE TITLE
[Bug] <Source Name>: <short description>

### ISSUE THREAD

**Issue by HumanityI** [jmir1/aniyomi-extensions#602]
---

## Device information
- Aniyomi version: Stable 0.12.3.6
- Android version: 10

## Source information
- Name: Animepahe
- Extension version: English 12.16

## Steps to reproduce
1. have an anime in the library that was added in the previous version of the extension
2. watch anime or download

### Expected behavior
Be able to watch anime or able to download it

### Actual behavior
Error HTTP 404

## Other details
Webview does work. 
And if I add it in the library once again, it works

**Comment by jmir1** [comment]
refresh the episode list.
