### ISSUE TITLE
[Feature Request] <9anime>: Include uncensored episodes

### ISSUE THREAD

**Issue by hoang-himself** [jmir1/aniyomi-extensions#643]
## What feature should be added to this source?

Some animes have separate censored and uncensored versions, which 9anime shows as the same episode but with a small change in the URL.

Sample:

```text
/watch/harem-in-the-labyrinth-of-another-world.80xno/ep-1
/watch/harem-in-the-labyrinth-of-another-world.80xno/ep-1-uncen
```

However, trying to scrape two times the number of episodes in efficient. So far, I can only think that there should be two source entries, each will scrape exclusively the censored and uncensored episodes.

**Comment by Samfun75** [comment]
Is this still applicable with the new version? All episodes can be scrapped at once.

**Comment by hoang-himself** [comment]
I just upgraded the extension to v13.15 and it's working as intended. Thanks for the heads up.
