### ISSUE TITLE
[Bug] OtakuDesu : can't play

### ISSUE THREAD

**Issue by MuhaGX** [jmir1/aniyomi-extensions#648]
## Device information
- Aniyomi version: 
App version: 0.12.3.7 (standard, 24c1ba6, 72, 2022-07-09T09:48Z)
Android version: 7.1.2 (SDK 25)
Android build ID: NRD90M.G955FXXU1AQJ5
Device brand: samsung
Device manufacturer: samsung
Device name: dream2lte
Device model: SM-G955F
Device product name: dream2ltexx
(Bluestacks Emulator)

- Android version: 7.1.2 (SDK 25)

## Source information
- Name: OtakuDesu
- Extension version: 12.12

## Other details

https://user-images.githubusercontent.com/70599137/178457558-2bda1173-61fd-4b1d-b6ff-86a1b82bb774.mp4

**Comment by willyreza** [comment]
please fix it

**Comment by DemuraAIdev** [comment]
Pls fix this
