### ISSUE TITLE
[Source Request] <AnimeFLV (original)>

### ISSUE THREAD

**Issue by edmxn** [jmir1/aniyomi-extensions#660]
## Source website
- Name: AnimeFLV (Original)
- Link: m.animeflv.net
- Language(s): Español

## Other details
There already exists a source called AnimeFLV, but that is a blatant copy of this site, this is the original link of "AnimeFLV", there are many anime that have not been uploaded in the existing source, so it would be better to add this one.

"AnimeFLV" has two links/webs only, they are these:
m.animeflv.net
www3.animeflv.net/

**Comment by miguelantonioe** [comment]
The AnimeFlv extension was using the original site "animeflv.net" but some developer in the past thought that "animeflv.cc" was better.  In the next few days I will be changing the source.

**Comment by edmxn** [comment]
> The AnimeFlv extension was using the original site "animeflv.net" but some developer in the past thought that "animeflv.cc" was better. In the next few days I will be changing the source.

The extension already existing in Aniyomi has less content than the original one, but well, maybe it had its reasons
