### ISSUE TITLE
[Source Request] haho.moe

### ISSUE THREAD

**Issue by ArjixWasTaken** [jmir1/aniyomi-extensions#72]
## Source website
- Name: haho.moe
- Link: haho.moe
- Language(s): english

## Other details
It's literally the same site as tenshi.moe, but with hentai instead.
Quite literally all you need to do is copy paste tenshi.moe code and replace the links.

**Comment by jmir1** [comment]
closed by a3745137de3ee7c2419fe607aed773a7f1e01fe5
very good suggestion! that was pretty easy haha...
now i just need a logo for it, i dont know how @as280093 does it

**Comment by as280093** [comment]
[ic_launcher.zip](https://github.com/jmir1/aniyomi-extensions/files/7120268/ic_launcher.zip)
@jmir1 here needed to recreate whole from just 16x16 px favicon

**Comment by jmir1** [comment]
Wow that is really impressive, thanks so much!!
