### ISSUE TITLE
Expected start of object '{', but had 'EOF' instead...

### ISSUE THREAD

**Issue by ItamiWasTaken** [jmir1/aniyomi-extensions#753]
### Source information and language

9anime 13.20 English

### Steps to reproduce

1. Browse 9anime in app
2. try to load any anime

### Expected behavior

anime loads, downloads, and plays without issue

### Actual behavior

the same error message "Expected start of object '{', but had 'EOF' instead..." always appears either in a toast or notification if you try to download an episode

### Aniyomi version

0.12.3.7

### Android version

Android 12.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ThePainReminder** [comment]
The weird thing is that sometimes the extension works fine for an hour or so but then it gets messed up agn.
