### ISSUE TITLE
9anime uninstalling and error

### ISSUE THREAD

**Issue by Latenighthunter** [jmir1/aniyomi-extensions#781]
### Source information and language

9anime 13.21 (en)

### Steps to reproduce

1. open the app
2. go to anime
3. update anime or click to watch an episode

### Expected behavior

should play the  episode 

### Actual behavior

it give me an Expected start of object '{', but had 'EOF' instead orror when refreshed anime or i click to watch an anime

### Aniyomi version

Aniyomi v0.12.3.7

### Android version

android 7

### Other details

the extension also uninstalls itself after some time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by sinnghabhay80** [comment]
I second this one
