### ISSUE TITLE
[Bug] <Animepahe>: <Episodes will not play>

### ISSUE THREAD

**Issue by HandyManny2499** [jmir1/aniyomi-extensions#782]
## Device information
- Aniyomi version: Stable 0.12.3.7
- Android version: 13

## Source information
- Name: AnimePahe
- Extension version: 13.17

## Steps to reproduce
1. Open the AnimePahe extension
2. Select any show
3. Open any episode

### Expected behavior
Episode should play as normal with no timeouts.

### Actual behavior
The extension will stay on the loading icon, and the episode will not play. It will eventually timeout with the error "Failed to bypass cloudflare".

## Other details
I have followed troubleshoot guide, I have cleared cookies and cache, I have uninstalled and reinstalled both the app and the extension, but it still will not play. I have even checked the actual website and there is nothing wrong with it.

**Comment by tshrpl** [comment]
have you tried toggling the `Use HLS links` setting?

**Comment by HandyManny2499** [comment]
> have you tried toggling the `Use HLS links` setting?

I've tried looking for that option but do not see it.

**Comment by HandyManny2499** [comment]
I found the setting and it worked. Thank you for the suggestion

**Comment by tshrpl** [comment]
@jmir1 
the above use says:
> I have followed troubleshoot guide

and yet they were unable to fix a simple problem which was toggling an `HLS Links` setting, specific to the animepahe extension

and there is no mention of HLS on the [troubleshooting page](https://aniyomi.jmir.xyz/help/guides/troubleshooting)

i think adding something similar to the following point to the `Diagnosis` steps list could help people a bit
- check the settings for the specific extension(s)
`Browse → Anime Extensions/Manga Extensions → Installed → (extension name) Settings`
check for any relevant settings/workarounds for your error (Timeout/links not found/IO error etc.), (if unsure ask on discord/reddit/github issues for support **after** trying the rest of the steps)

i also think adding this point right before would be best
- Ask other users to try the action that gives you the error.
or
- Try the following at `More → settings Settings → code Advanced`

is the best option
