### ISSUE TITLE
[Feature Request] Add A "Preferred Quality" option in extension settings

### ISSUE THREAD

**Issue by mnabid** [jmir1/aniyomi-extensions#79]
Currently, there is a quality selector under the internal video player. But if I play videos with an external player, Aniyomi will grab the highest quality right off the bat. And there's no way to change the quality afterwards (because external player).

**Would it be possible to add a `Preferred Quality` option in the extension settings (or in the app settings)?**

That way, if I set it to `720p`, the extension will search for the 720p stream first. If `720p` is unavailable, then it will try `480p -> 360p -> 1080p`. So...it'll just loop around in a circle (starting from the preferred quality) until it finds an available stream.

***P.S.:** Not all sources provide multi-quality streams (e.g. Twist), so it's better to add this option in the extension settings rather than app settings.*

**Comment by jmir1** [comment]
i added something like that in the gogoanime extension for now.
