### ISSUE TITLE
Issue [Onepace]

### ISSUE THREAD

**Issue by Arghadatta** [jmir1/aniyomi-extensions#807]
### Source information and language

Onepace 13.5

### Steps to reproduce

Just try one video.
It shows error response code 404

### Expected behavior

Plays the video

### Actual behavior

Error:Respond code 404

### Aniyomi version

0.12.3.8

### Android version

Android 12

### Other details

@Diegopyl1209
It is happening for a while.also i updated the extension that came out recently this day.and also have the latest aniyomi.
But the issue is consistant,
![Screenshot_20220826-223641_Aniyomi](https://user-images.githubusercontent.com/78955676/186952891-09effc29-4a52-43fc-bd75-ae4ed7276647.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Diegopyl1209** [comment]
ok
