### ISSUE TITLE
9anime does not work still, after new update

### ISSUE THREAD

**Issue by Tasenova99** [jmir1/aniyomi-extensions#825]
### Source information and language

9anime

### Steps to reproduce

Click on any stream, and it just says "bruh"

### Expected behavior

Play the stream

### Actual behavior

spats out "bruh"

### Aniyomi version

0.12.3.8

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Nintenstation** [comment]
Thank you for reporting this!! I really hope they can notice it and they try to fix it, if possible. Wishing them luck.

**Comment by Jcross1029** [comment]
having the same issue, gets a update still does not work.
