### ISSUE TITLE
Cuevana

### ISSUE THREAD

**Issue by edmxn** [jmir1/aniyomi-extensions#828]
### Source name

Cuevana

### Source link

ww1.cuevana3.me

### Language

Español

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.jmir.xyz/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/jmir1/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by jasshira266** [comment]
#580 #565 Extension cave is already found, it would be good if you closed those requests.
Ya se encuentra cuevana de extensión, sería bueno que esas mismas peticiones que hiciste las cerraras:)
