### ISSUE TITLE
Zoro.to player

### ISSUE THREAD

**Issue by edmxn** [jmir1/aniyomi-extensions#847]
### Source information and language

zoro.to (experimental) 13.9

### Steps to reproduce

1. Open an episode
2. Wait for it to load

### Expected behavior

The video loads normally, including its subs

### Actual behavior

When trying to play a video in the extension, the message "Couldn't find any video links" appears when it loads perfectly on the web, obviously external players do not work either

### Aniyomi version

0.12.3.8

### Android version

Android 12

### Other details

This happens with all the animes in Zoro.to (in the extension)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by HarshSinha11** [comment]
I am having same issues
