### ISSUE TITLE
[Bug] <Animepahe>: <Animepahe extension says "error getting links" everytime>

### ISSUE THREAD

**Issue by SaqinNoor** [jmir1/aniyomi-extensions#88]
## Device information
- Tachiyomi version: 0.12.2.2
- Android version: 7

## Source information
- Name: Animepahe
- Extension version: 12.5

## Steps to reproduce
1. Open an anime using animepahe extension
2. Play it
3. It will say "error getting links" and quit the video

### Expected behavior
It should've played the video

### Actual behavior
It quits the video and says error getting links

## Other details
No other details.

**Comment by jmir1** [comment]
see this: https://github.com/jmir1/aniyomi/issues/166#issuecomment-920590545

**Comment by SaqinNoor** [comment]
> see this: [jmir1/aniyomi#166 (comment)](https://github.com/jmir1/aniyomi/issues/166#issuecomment-920590545)

Tried it. Doesn't work.
