### ISSUE TITLE
DopeBox not working 

### ISSUE THREAD

**Issue by qryptonique** [jmir1/aniyomi-extensions#880]
### Source information and language

DopeBox 13.9

### Steps to reproduce

Open via Browse
Click on any video
Select an episode 

### Expected behavior

Loads successfully 

### Actual behavior

An error occurs 
![Screenshot_20220920-144131](https://user-images.githubusercontent.com/109937170/191274945-26787daa-424d-4e8f-9150-f7846c045e06.png)

### Aniyomi version

App version: 0.12.3.8

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by SabaManjavidze** [comment]
Hi! i was recreating this extension in typescript and everything was going well until it was time to get the re-captcha key.
The re-captcha URL that is referenced currently no longer provides a key or any other info besides script tags. I don't have a solution. I'm just sharing what I know.

**Comment by HarshSinha11** [comment]
Try changing preferred domain in Browse --> Anime Extension --> DopeBox --> Settings

**Comment by qryptonique** [comment]
Thanks for attempting! @SabaManjavidze 
@HarshSinha11 I just tried that but got the same error.
