### ISSUE TITLE
HentaiMama still doesn't load the episodes of some entries after update 13.5

### ISSUE THREAD

**Issue by Palloxin** [jmir1/aniyomi-extensions#894]
### Source information and language

HentaiMama 13.5

### Steps to reproduce

NSFW warning
https://user-images.githubusercontent.com/75091899/193181436-85c2c861-dda3-4796-8c17-e59a23984d77.mp4
NSFW warning due to the nature of the extension.

### Expected behavior

Episodes of all entries load

### Actual behavior

Some entries episodes don't load

### Aniyomi version

r5237

### Android version

Android 8

### Other details

I already reported the issue/bug https://github.com/jmir1/aniyomi-extensions/issues/892 and it was closed because completed. i updated tge extension and the problem was still there.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by thatDudo** [comment]
Have you really updated the extension?
I dont have this problem anymore:
![Aniyomi](https://user-images.githubusercontent.com/58403773/193369136-8aa803e5-f28d-4418-bd9a-b731319e8c0e.png)

Please share the error message if it persists.

**Comment by Palloxin** [comment]
i disinstalled the extension and installed it again. @thatDudo

**Comment by thatDudo** [comment]
go to settings > advanced > clear chapter and episode caches
if it doesnt help maybe try clicking on the webview button bellow the thumbnail and see if the website even loads...

**Comment by Palloxin** [comment]
i deleted all the data of aniyomi and then restored a backup. now it works, my bad then
