### ISSUE TITLE
Add new extensions

### ISSUE THREAD

**Issue by xXCats** [jmir1/aniyomi-extensions#899]
### Source name

New extension for anime

### Source link

https://www.animeunity.tv/

### Language

Italian

### Other details

Hi among the anime extensions there is no  of the following sources where I usually watch anime:
AnimeUnity.tv you could add them.

https://www.animeunity.tv/

-Thank you

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.jmir.xyz/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/jmir1/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
closed by #1188
