### ISSUE TITLE
[Bug] Tenshi.moe : v12.12 Error update

### ISSUE THREAD

**Issue by Rohan-Somadder** [jmir1/aniyomi-extensions#90]
## Device information
- Tachiyomi version: Preview r4129
- Android version: Android 8.1

## Source information
- Name: Tenshi.moe
- Extension version: 12.12

## Steps to reproduce
1. Open browse
2. Try to update the  extension / Try to watch any episode with this extension

### Expected behaviour
The extension should update normally, and the episode should play

### Actual behaviour
1. After updating to the latest version tenshi.moe extension is not updating even the update is available
2. It repeatedly prompts retry
3. An new episode or previous un-downloaded episodes are also unplayable

**Comment by jmir1** [comment]
ok, the build script seems to have messed something up, i'm not sure how or why

**Comment by jmir1** [comment]
it seems that sometimes, this file: https://github.com/jmir1/aniyomi-extensions/blob/repo/index.min.json isn't getting updated propely
not sure why but this mostly fixes itself after the next push to the repo (which i just did) let's see if it gets fixed

**Comment by jmir1** [comment]
update: it seems to work now. just refresh the extensions list and install the update.
(if it doesn't show version 12.23 then your cache is outdated. just clear your app cache and do it again)

**Comment by Rohan-Somadder** [comment]
Thanks, it's resolved now.
