### ISSUE TITLE
Turkish Subtitle

### ISSUE THREAD

**Issue by chrxllo** [jmir1/aniyomi-extensions#920]
### Source name

Turk anime

### Source link

https://www.turkanime.co/

### Language

Turkish

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.jmir.xyz/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/jmir1/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
fe53f7a8c1068739728d15a5c9d0b51b2b7c3353
