### ISSUE TITLE
fix OtakuDesu

### ISSUE THREAD

**Issue by Yuii02** [jmir1/aniyomi-extensions#954]
### Source name and language

OtakuDesu [Indonesian]

### Describe your suggested feature

please fix

### Other details

haven't noticed for too long

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MoonLGH** [comment]
what the bug...
