### ISSUE TITLE
[Source Request] <Fênixsub>

### ISSUE THREAD

**Issue by Lukyzzz** [jmir1/aniyomi-extensions#975]
## Fênixfansub
- Name: Fênixsub
- Link: https://fenixfansub.net/
- Language(s): PT-BR

## Other details

It's cool cause this source has uncensored and even hentai as well as normal animes and all, there's not much option of uncensored or hentai extensions on pt-br so.....

**Comment by Claudemirovsky** [comment]
Unfortunately creating a full FenixSub extension may be impossible, as this source does not stream, but only distributes .RAR files for DOWNLOAD.
In other words, to watch an episode, it is necessary to download it, extract it, and play the extracted episode, something that the current aniyomi API would not allow us to do (nor should it). Even if it did, this process would be painfully slow compared to any other extension, so it would be practically useless.

**Comment by Lukyzzz** [comment]
Understandable
![20221025_201204.jpg](https://user-images.githubusercontent.com/28473476/197899127-673d8061-d772-482a-a8a0-f70975d1f01b.jpg)
